import "./globals.css";
import { VT323 } from "next/font/google";
import localFont from 'next/font/local'

const vtCustomFont = localFont({ src: '../res/vt323custom.otf' ,variable:"--font-custom-vt"})

const vtFont = VT323({ weight: "400", style: "normal", variable: "--font-vt", display: "swap", subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={vtFont.variable}>
      <body>{children}</body>
    </html>
  );
}
